version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: nexus_user
      POSTGRES_PASSWORD: nexus_pass
      POSTGRES_DB: nexus_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    environment:
      DATABASE_URL: postgres://nexus_user:nexus_pass@postgres:5432/nexus_db
      JWT_SECRET: supersecretkey
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - postgres

volumes:
  postgres-data:
